modLoader="javafml"
loaderVersion="[30,)"
# issueTrackerURL=""

[[mods]] #mandatory
modId="endermagnet"
version="1.15.1-3.0.0"
displayName="Ender Magnet"
# updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/ender-magnet"
# logoFile="logo.png"
# credits=""
authors="Ruuubi"
description='''Adds magnets that pull nearby items to the player'''

[[dependencies.endermagnet]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.41,)"
    ordering="NONE"
	side="BOTH"